<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>hnurm_radar</name>
  <version>0.0.0</version>
  <description>HNURM Radar detection node with TensorRT acceleration</description>
  <maintainer email="your_email@example.com">syh</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>pcl_conversions</depend>
  <depend>livox_ros_driver2</depend>
  <depend>example_interfaces</depend>
  <depend>cv_bridge</depend>
  <depend>std_msgs</depend>
  <depend>yaml-cpp</depend>
  <depend>nlohmann_json</depend>
  <depend>libopencv-dev</depend>
  <build_depend>detect_result</build_depend>
  <exec_depend>detect_result</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>